#!/usr/bin/env python3
"""Fail a commit that names a typeface absent from the maintainer's Adobe library.

Issue #204. The maintainer's standing constraint — *every face in the final design is
in the ``audio-lab`` Adobe library (project ``zol6gng``); a face absent from it is
definitionally wrong* — was stated repeatedly, was never wired to anything, and so
``ArialNarrow-Bold`` reached ``main`` in a builder marked **IN FORCE** and was caught
by the maintainer two merges later (#202).

This is a gate, not a rule: it runs from ``.pre-commit-config.yaml`` and exits non-zero
without anyone choosing to check. It reads ``brand/fonts-manifest.json`` (generated by
``scripts/generate_fonts_manifest.py``) and needs no fonts installed, so it works
identically in CI, in a cloud session, and on a fresh clone.

Scope, stated plainly rather than implied
-----------------------------------------
**What is checked.** Hyphenated PostScript-shaped names — ``Family-Style`` — in

* string literals in ``tools/brand/**/*.jsx``
* backticked code spans in ``brand/**/*.md``

That shape is exactly what a builder writes when it asserts a specific cut, and it is
the shape of ``ArialNarrow-Bold``, the miss this gate exists to catch.

**What is deliberately not checked, and why.**

*Prose in markdown.* ``brand/20260801-toldstraight-approved-card-standard.md`` records
the #202 correction by naming the wrong faces in prose — *"named Arial Narrow Bold and
Courier New Bold. That was wrong twice over."* A gate reading prose would fail on the
document that fixes the bug. Backticked spans are where that file puts real PostScript
names, so that is what is read.

*Bare family stems* such as ``"tradegothicnext"`` or ``"LetterGothicStd"``. The
builders resolve faces through fuzzy ``require``/``prefer`` stem lists; a stem is a
search term, not a face assertion, and flagging stems would fire on every builder in
the tree. A face asserted by stem alone is therefore outside this gate's reach — a
real limit, recorded here rather than papered over.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "brand" / "fonts-manifest.json"

DEFAULT_GLOBS = ("tools/brand/**/*.jsx", "brand/**/*.md")

# Quoted string literals in JSX/JavaScript. Font names never contain a quote or a
# newline, so a non-greedy same-line match is sufficient and avoids dragging in the
# rest of the file on an unbalanced quote.
JSX_STRING = re.compile(r"""(['"])([^'"\n]{2,120})\1""")

# Backticked code spans in markdown.
MD_CODE_SPAN = re.compile(r"`([^`\n]{2,120})`")

# A PostScript-shaped face reference: CamelCase stem, then one or more hyphenated
# style segments. The stem must be at least four characters and carry a lowercase
# letter, which is what separates `TradeGothicNextLTPro-BdCn` and `ArialNarrow-Bold`
# from the exhibit-card IDs (`TS-H01`), asset slugs (`favicon-180`, `ep03-cover`) and
# mode flags (`locked-lettergothic`) that live in the same files.
FACE_TOKEN = re.compile(r"^(?P<stem>[A-Za-z][A-Za-z0-9]{3,})(?:-[A-Za-z0-9]+)+$")


def looks_like_face(token: str) -> bool:
    """True when ``token`` has the shape of a PostScript face name."""
    match = FACE_TOKEN.match(token)
    if match is None:
        return False
    stem = match.group("stem")
    # An all-caps stem is an identifier or an acronym code, not a family name.
    if not any(char.islower() for char in stem):
        return False
    # A family stem starts with a capital in every Adobe PostScript name.
    return stem[0].isupper()


def normalise(name: str) -> str:
    """Collapse a face name to its comparison key.

    ``Trade Gothic Next LT Pro Bold Condensed``, ``TradeGothicNextLTPro-BdCn`` and
    ``ArialNarrow-Bold`` versus ``Arial Narrow Bold`` all have to compare sanely, so
    spaces, hyphens and case are dropped. The abbreviated PostScript cut (``BdCn``)
    will not equal the spelled-out style, which is why the manifest contributes
    several keys per face rather than one.
    """
    return re.sub(r"[^a-z0-9]", "", name.lower())


def load_manifest(path: Path) -> tuple[set[str], list[dict], dict]:
    """Return (known keys, exemption records, raw manifest)."""
    if not path.exists():
        raise SystemExit(
            f"{path} is missing. Generate it on a machine with the library synced:\n"
            "  python3 scripts/generate_fonts_manifest.py"
        )
    manifest = json.loads(path.read_text())
    known: set[str] = set()
    for face in manifest.get("faces", []):
        family = face.get("family", "")
        style = face.get("style", "")
        for candidate in (
            face.get("postscript_name", ""),
            face.get("full_name", ""),
            family,
            f"{family}{style}",
        ):
            if candidate:
                known.add(normalise(candidate))
    exemptions = manifest.get("exempt", [])
    for entry in exemptions:
        known.add(normalise(entry["name"]))
    return known, exemptions, manifest


def extract(path: Path) -> list[tuple[int, str]]:
    """Return (line number, candidate face token) pairs found in ``path``."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []

    pattern = MD_CODE_SPAN if path.suffix.lower() == ".md" else JSX_STRING
    group = 1 if path.suffix.lower() == ".md" else 2

    found: list[tuple[int, str]] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        for match in pattern.finditer(line):
            token = match.group(group).strip()
            if looks_like_face(token):
                found.append((line_number, token))
    return found


def resolve_targets(paths: list[str]) -> list[Path]:
    """Map the caller's paths (or the default globs) to files worth scanning."""
    if paths:
        selected = [Path(p) for p in paths]
    else:
        selected = []
        for glob in DEFAULT_GLOBS:
            selected.extend(sorted(REPO_ROOT.glob(glob)))
    keep: list[Path] = []
    for path in selected:
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        try:
            relative = path.resolve().relative_to(REPO_ROOT)
        except ValueError:
            continue
        parts = relative.parts
        in_builders = parts[:2] == ("tools", "brand") and suffix == ".jsx"
        in_brand_docs = parts[:1] == ("brand",) and suffix == ".md"
        if in_builders or in_brand_docs:
            keep.append(path)
    return keep


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths", nargs="*", help="Files to check (pre-commit passes these)."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=MANIFEST_PATH,
        help="Manifest to check against.",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print every face reference found, then exit 0.",
    )
    args = parser.parse_args()

    known, exemptions, manifest = load_manifest(args.manifest)
    targets = resolve_targets(args.paths)

    violations: list[tuple[Path, int, str]] = []
    seen_total = 0
    for path in targets:
        for line_number, token in extract(path):
            seen_total += 1
            if args.list:
                status = "ok " if normalise(token) in known else "MISS"
                print(f"{status} {path.relative_to(REPO_ROOT)}:{line_number}: {token}")
                continue
            if normalise(token) not in known:
                violations.append((path, line_number, token))

    if args.list:
        print(f"\n{seen_total} face references across {len(targets)} files.")
        return 0

    if not violations:
        print(
            f"Brand fonts OK: {seen_total} face references across {len(targets)} files, "
            f"all present in the library manifest "
            f"({manifest.get('family_count')} families / {manifest.get('face_count')} faces"
            + (f", {len(exemptions)} exemptions" if exemptions else "")
            + ")."
        )
        return 0

    print(
        "Face(s) named that are NOT in the maintainer's audio-lab Adobe library "
        "(project zol6gng). The standing constraint is that a face absent from the "
        "library is definitionally wrong:\n",
        file=sys.stderr,
    )
    for path, line_number, token in violations:
        print(
            f"  {path.relative_to(REPO_ROOT)}:{line_number}: {token}", file=sys.stderr
        )
    print(
        "\nResolve by one of:\n"
        "  1. Use a face that is in the library "
        "(python3 scripts/check_brand_fonts.py --list shows what resolves).\n"
        "  2. Activate the face in Creative Cloud, then regenerate:\n"
        "     python3 scripts/generate_fonts_manifest.py\n"
        "  3. If the name is a deliberate non-library fallback, add it to the\n"
        "     'exempt' block of brand/fonts-manifest.json WITH a reason. That is a\n"
        "     visible diff line the maintainer reviews — which is the point.\n"
        "\nDo not bypass with --no-verify.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
